### PR TITLE
Add a command line switch to easily sample from prior

### PR DESCRIPTION
**Pull request by Anaphory**
Add a command line switch to the `beastling` program that allows to generate a `sample_from_prior` config.xml without having to change the beastling config. To avoid file name duplication, this generated file differs from the original config.xml by a suffix of "_prior" if there is none yet.

If the basename already ends in `_prior`, we assume someone knows what they are doing and do not change it!

`--prior` takes precedent over `sample_from_prior=False`, because we don't know if it's that way because it was the default value or was set, and generally things specified on the CLI should have preference over something in a random file.

### CODE REVIEW

**Comment by Anaphory** [comment]
There was a problem with language filtering. It appears that `language_filter` got ignored after construction. I added a commit that tries to fix it. (I'm still not good with only pushing tested commits – It does not fix it, because I mistyped something.)

**Comment by Anaphory** [comment]
Argh, ignore that last commit. It comes from being awful at testing and not actually reading how the basemodel api has changed.

**Comment by lmaurits** [comment]
Are you sure I should ignore all of that last commit?  The change to `self.languages = sorted(self.languages)` does seem wrong, but the change to `missing_langs = self.languages.difference(tree_langs)` seems correct?  Naturally there should be a test to guide me on this, but I don't think there is...

**Comment by Anaphory** [comment]
Hm. The last commit might contain relevant changes, but it definitely also contains irrelevant ones. I (or you, if you would like to get it done soon – my next two weeks will be busy otherwise) need to check it, and write associated tests. (And I need to get it into my workflow to run tests and check their results before pushing publicly.)

**Comment by Anaphory** [comment]
I think this is obsolete now.

**Pull request closed without merging**
