### PR TITLE
Stackable interpolation

### PR DESCRIPTION
**Pull request by Anaphory**
Activate interpolation in a way that's useful for `beastling`.

This pull-request contains a very generic modification of `ConfigParser`, which does only change a small implementation detail, so not much of the code is covered by tests.

### CODE REVIEW

**Comment by Anaphory** [comment]
This got rebased on top of #127

**Comment by lmaurits** [comment]
Ah, shoot, should I not have merged #127 and just done this one due to the rebasing?

**Comment by Anaphory** [comment]
That doesn't really matter, you did what I intended:
This one needs close reading because it contains an untested `ConfigParser` mixin. I want to give you some tests for that one first, I think.
Therefore I assumed you would merge #127 first, and I rebased this on top so that for once we would not have a million parallel branches, but just 999999 ;-)

**Comment by Anaphory** [comment]
Let me close this thing and give you some clean pull requests for the remaining issues.

**Pull request closed without merging**
