### PR TITLE
Prepare ancestral state reconstruction & Cleaner reading of CLDF data

### PR DESCRIPTION
**Pull request by Anaphory**
# ASR
 - Implement ancestral state reconstruction, both for clades and for the whole tree.
 - Add a way to specify language groups, with tests.
 - Check the output generated by beast, at least by checking that files with the expected name are written.

# CLDF
 - Update CLDF support to reading 1.0 datasets, both specified by metadata and metadata-free.
 - Include example data (not completely clean yet?)
 - Include tests
 - In tests, show how older beastling CLDF files can be read using the new reader, by specifying a metadata json file.

### CODE REVIEW

**Comment by Anaphory** [comment]
Hm, this fails somewhere in a region I don't think I touched due to unicode issues with 2.7:
[travis](https://travis-ci.org/lmaurits/BEASTling/jobs/301430696#L1541) saysthat https://github.com/lmaurits/BEASTling/blob/affdd4e7c3d0c521f3e398a2c3b841848fa780ea/beastling/fileio/datareaders.py#L38 leads to an error in [clldutils:dsv.py](https://github.com/clld/clldutils/blob/d6556797a238dd7ce4b5debf87c2eb1bee2d4a1b/clldutils/dsv.py#L170)
because

    TypeError: "delimiter" must be string, not unicode

I understand neither whey delimiter must be string, nor why it isn't.

**Comment by Anaphory** [comment]
Hm. I thought it might be `unicode` because that's what `fix_kw` does:
https://github.com/clld/clldutils/blob/d6556797a238dd7ce4b5debf87c2eb1bee2d4a1b/clldutils/dsv.py#L31

But actually, that only converts to “binary”, which is specifically not `unicode`, but `str` for 2.7 and `bytes` for 3. So where does the `unicode` type come from?

**Comment by xrotwang** [comment]
Can you paste the full stacktrace?

**Comment by Anaphory** [comment]
Only from the [travis](https://travis-ci.org/lmaurits/BEASTling/jobs/301430696#L1541) run I already linked above:
```
Traceback (most recent call last):
  File "/home/travis/virtualenv/python2.7.13/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/travis/build/lmaurits/BEASTling/tests/beastrun_tests.py", line 132, in _do_test
    xml = beastling.beastxml.BeastXml(config)
  File "/home/travis/build/lmaurits/BEASTling/beastling/beastxml.py", line 34, in __init__
    self.config.process()
  File "/home/travis/build/lmaurits/BEASTling/beastling/configuration.py", line 448, in process
    self.instantiate_models()
  File "/home/travis/build/lmaurits/BEASTling/beastling/configuration.py", line 856, in instantiate_models
    model = mk.MKModel(config, self)
  File "/home/travis/build/lmaurits/BEASTling/beastling/models/mk.py", line 12, in __init__
    BaseModel.__init__(self, model_config, global_config)
  File "/home/travis/build/lmaurits/BEASTling/beastling/models/basemodel.py", line 50, in __init__
    self.data = load_data(self.data_filename, file_format=model_config.get("file_format",None), lang_column=model_config.get("language_column",None), value_column=model_config.get("value_column",None))
  File "/home/travis/build/lmaurits/BEASTling/beastling/fileio/datareaders.py", line 47, in load_data
    with UnicodeDictReader(filename, dialect=dialect) as reader:
  File "/home/travis/virtualenv/python2.7.13/lib/python2.7/site-packages/clldutils-1.13.10-py2.7.egg/clldutils/dsv.py", line 170, in __enter__
    self.reader = csv.reader(self.f, **self.kw)
TypeError: "delimiter" must be string, not unicode
```

```
Traceback (most recent call last):
  File "/home/travis/build/lmaurits/BEASTling/tests/fileio_tests.py", line 22, in test_load_data
    data = load_data(p)
  File "/home/travis/build/lmaurits/BEASTling/beastling/fileio/datareaders.py", line 47, in load_data
    with UnicodeDictReader(filename, dialect=dialect) as reader:
  File "/home/travis/virtualenv/python2.7.13/lib/python2.7/site-packages/clldutils-1.13.10-py2.7.egg/clldutils/dsv.py", line 170, in __enter__
    self.reader = csv.reader(self.f, **self.kw)
TypeError: "delimiter" must be string, not unicode
```

**Comment by xrotwang** [comment]
The only possibility I see for a delimiter keyword to make it around the `fix_kw` function is via this line:
https://github.com/Anaphory/BEASTling/blob/5bf21b929702ead01c62c2c51f819a4030224971/beastling/fileio/datareaders.py#L40
Do you know which data file is read when the test fails?

**Comment by xrotwang** [comment]
Note that the Python 2.7 docs for `csv.Sniffer` advise opening the file with mode `rb` - not as you do, in text mode.

**Comment by xrotwang** [comment]
```python
Python 2.7.6 (default, Jun 22 2015, 17:58:13) 
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import csv
>>> from clldutils.dsv import reader
>>> class M(csv.Dialect):
...   delimiter = u'\t'
... 
>>> r = reader([], dialect=M())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/csv.py", line 48, in __init__
    self._validate()
  File "/usr/lib/python2.7/csv.py", line 55, in _validate
    raise Error(str(e))
_csv.Error: "delimiter" must be string, not unicode
```

**Comment by Anaphory** [comment]
In python 3, `rb` does not work for the sniffer. Does that mean we want something like this?

```
if sys.version_info[0] == 2: # pragma: no cover
    def sniff(filename):
        """Read the beginning of the file and guess its csv dialect.

        Parameters
        ----------
        filename: str or pathlib.Path
            Path to a csv file to be sniffed

        Returns
        -------
        csv.Dialect
        """
        with Path(filename).open("rb") as fp:
            # On large files, csv.Sniffer seems to need a lot of datta to make a
            # successful inference...
            sample = fp.read(1024)
            while True:
                try:
                    return csv.Sniffer().sniff(sample, [",", "\t"])
                except csv.Error:
                    sample += fp.read(1024)
else:
    def sniff(filename):
        """Read the beginning of the file and guess its csv dialect.

        Parameters
        ----------
        filename: str or pathlib.Path
            Path to a csv file to be sniffed

        Returns
        -------
        csv.Dialect
        """
        with Path(filename).open("r") as fp:
            # On large files, csv.Sniffer seems to need a lot of datta to make a
            # successful inference...
            sample = fp.read(1024)
            while True:
                try:
                    return csv.Sniffer().sniff(sample, [",", "\t"])
                except csv.Error:
                    sample += fp.read(1024)
```

**Comment by xrotwang** [comment]
Well, you probably want something like
```python
with Path(filename).open("rb" if PY2 else "r") as fp:
```
but yes, that's how ugly cross-version CSV is in python :)

**Comment by xrotwang** [comment]
Note: The above is using six' `PY2` constant.

**Comment by Anaphory** [comment]
I used that, I'm just writing some tests for that `sniff` function.

**Comment by lmaurits** [comment]
Thanks both of you for your work on this!

**Comment by lmaurits** [comment]
@Anaphory In your opinion does merging this close #128, #145 or #172?

**Comment by Anaphory** [comment]
The ascertainment correction bits of #128 are still missing, as are documentation for reconstruction of single ancestors and of the whole tree.

**Comment by lmaurits** [comment]
Argh, of course.

**Pull request merged**
