### PR TITLE
Add preliminary support for reading CLDF-1.0 datasets

### PR DESCRIPTION
**Pull request by Anaphory**
Preliminary, because:
 - Only word lists
 - Not systematically tested for separate CognateTable
 - Utterly untested for other shapes
 - Insufficient auto-recognition

This should probably not be merged yet, but you should at least know how I would try to make it work.

### CODE REVIEW

**Comment by Anaphory** [comment]
Okay, among other things we would need to teach Travis to import clldutils/pycldf.

**Comment by lmaurits** [comment]
Thanks for making a start on this!  I'll have a look at it quite soon.

Once we have code making use of pycldf, it should be added to BEASTling's `setup.py` file as part of `install_requires`, in the same way that clldutils already is.  If we do that, Travis should install it (assuming it's in PyPi) before running any tests.

**Comment by lmaurits** [comment]
I guess by "insufficient auto-recognition" what you meant was that ideally instead of having to specify `cldf-wordlist` as the file format, one should just be able to specify `cldf` and the CLDF dataset itself should be able to tell BEASTling whether its a Wordlist or a Structure Dataset?

**Comment by Anaphory** [comment]
> I guess […]

Yes, also the location and interpretation of cognate data, BorrowingTables, column names, and anything else that is implicitly given in the CLDF JSON file but ignored for the moment.

**Comment by Anaphory** [comment]
Oops. `master` contained more changes than I thought, so I merged this in – but I meant this to be a separate pull request.

Shall I split this?

**Comment by xrotwang** [comment]
looks ok to me.

**Pull request merged**
