### PR TITLE
Fix encoding issue in datareaders.sniffer

### LINKED ISSUE #227: Encoding in tutorial file
I'm working though the tutorial atm.
Can somebody please advise what encoding to choose in the text editor?
UTF-8 gives me a decoding error:
> return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 66: character maps to <undefined> 

UTF-16 a missing header:
> File "C:\Users\PPLS User\AppData\Local\Programs\Python\Python37\lib\site-packages\configparser-3.5.0-py3.7.egg\backports\configparser\__init__.py", line 1101, in _read
    raise MissingSectionHeaderError(fpname, lineno, line)
backports.configparser.MissingSectionHeaderError: File contains no section headers.

Win10, Python 3.7.1 64bit

Thank you very much in advance!

### PR DESCRIPTION
**Pull request by Anaphory**
Fixes #227

### CODE REVIEW

**Comment by xrotwang** [comment]
I recently came across a similar problem with the csv sniffer. It's really annoying how difficult cross-platform csv manipulation seems to be.

**Comment by Anaphory** [comment]
This was also affected by #215 so I pushed the same fix that helped there.

**Comment by Anaphory** [comment]
The latest commit fails in Python2.7, because the dialect

    (Pdb) vars(self.kw['dialect'])
    {'__module__': 'csv', 'lineterminator': '\r\n', 'skipinitialspace': False, 'quoting': 0, 'encoding': 'ascii', '_name': 'sniffed', 'delimiter': u',', 'quotechar': u'"', '__doc__': None, 'doublequote': False}

passed to `csv.reader` – `python2.7/site-packages/csvw/dsv.py`:

    224  ->	        self.reader = csv.reader(self.f, **self.kw)

contains unicode objects for delimiter and quotechar, and that is apparently not allowed. I don't know how to fix that.

**Comment by xrotwang** [comment]
csvw.dsv handles that somewhat. But I'd think at this point, dropping py2
may be more reasonable.

Am Fr., 23. Nov. 2018, 15:15 hat Gereon Kaiping <notifications@github.com>
geschrieben:

**Comment by lmaurits** [comment]
The dialect object we get back from the sniffer now has an encoding attribute, thanks to Gereon's recent commit, right?  Can't we just use that to encode the delimiter and quote char before handing it to the reader?  Or is the dialect immutable?

**Review by xrotwang — APPROVED** [review]

**Comment by xrotwang** [comment]
I think we don't actually need the encoding to be used - the relevant entries are supposed to be ASCII encoded strings anyway. But yes, the dialect object would be the place to encode these things for `PY2`.

**Comment by Anaphory** [comment]
> Or is the dialect immutable?

If the dialect was immutable, I could not actually stuff an `encoding` into it :)

It should really just be converting some `u','` to `','` in Py2 or something very similar, but I was not sure yet why it happened in the first place and where the best place to fix in in the most canonical way would be.

**Comment by xrotwang** [comment]
AFAICT this PR can be closed. @Anaphory agree?

**Pull request closed without merging**
