### PR TITLE
add python >= 3.3 compatible version of xml comment parser

### PR DESCRIPTION
**Pull request by xrotwang**
This was a bit more painful than expected, but seems to work now. I'll add more tests later, but the test suite passes on my end for py2.7 and py3.4.

### CODE REVIEW

**Comment by lmaurits** [comment]
I'm getting the following test failure?

```
======================================================================
ERROR: test_extractor (tests.extractor_test.Tests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/luke/Development/BEASTling/tests/extractor_test.py", line 28, in test_extractor
    res = beastling.extractor.extract(xmlfile)
  File "/home/luke/Development/BEASTling/beastling/extractor.py", line 59, in extract
    messages.append(write_config(beastling_confs[0].text, overwrite))
  File "/home/luke/Development/BEASTling/beastling/extractor.py", line 83, in write_config
    if not os.path.exists(filename.parent):
  File "/home/luke/Development/BEASTling/.tox/py27/lib/python2.7/genericpath.py", line 18, in exists
    os.stat(path)
TypeError: coercing to Unicode: need string or buffer, PosixPath found

```

**Comment by xrotwang** [comment]
sorry. will fix. I started to use `clldutils.path.Path` objects instead of filesystem paths as strings in a couple of places, but apparently haven't done so consistently. It's a bit weird though, that tests passed on my side ...

**Comment by lmaurits** [comment]
Strange, I have only made a small change to beastling/configuration.py on my end, no merge conflicts, so I'm not sure what else on my end could be causing it.

**Comment by xrotwang** [comment]
I guess one of the other `return` statements in `write_config` were hit on my end. Tests behave a bit non-deterministic if files in current working dir may make a difference.

**Pull request merged**
