### PR TITLE
 ported tests to pytest 

### PR DESCRIPTION
**Pull request by xrotwang**
I de-activated the assertions for the currently failing beastrun tests, see #235

### CODE REVIEW

**Comment by lmaurits** [comment]
So what do I run to do these tests locally instead of my old `nosetests`?

**Comment by xrotwang** [comment]
You install all test/dev requirements running `pip install -r requirements.txt`, and then simply `pytest`. Arguments for `pytest` are configured in `setup.cfg`.

**Comment by lmaurits** [comment]
Okay, I'm officially Pleased as Punch with this!  I just did a `pytest tests/fileio_tests.py` and it *only* ran the tests in that file and then quit.  Even though I'm, heaven forbid, not in a virtualenv!  This sounds like a ludicrously straightforward thing to get excited about, but literally none of our previous test setups have worked like this for me.

**Comment by xrotwang** [comment]
I think the test files got a lot simpler, too. So I'd say that's a good basis to move forward.

If you don't have stuff to fold into beastling right now, I'd have a go at removing all PY2 compat stuff, so we can startout with an even leaner codebase.

**Comment by lmaurits** [comment]
Nope, nothing to fold in for now.  Even though we now have `validate_ids()` in place, I'd like to start shifting toward a system where a lot of these IDs are generated programmatically, rather than being handwritten.  So I'm liable to be thinking about big future overhauls for a while, rather than hacking in random little bits and pieces.  In other words, this is a fine time to have a go at killing PY2.

**Comment by xrotwang** [comment]
Are you ok with also rolling in some xml creation refactoring?

**Comment by lmaurits** [comment]
Hmm, what did you have in mind?

**Comment by xrotwang** [comment]
I just wanted to replace all the `ET.SubElement` or `ET.Element` calls with calling a utility function, which can add some syntactic sugar to
- pass in node text
- pass in python objects as attribute values which will be converted appropriately (e.g. lists as value for a `range` attribute will be `",".join`ed).

And add explicit element functions named after the tag names to an xml module, so that the tab-completion in the IDE prevents mistyping tag names.

**Comment by lmaurits** [comment]
Okay, sounds good!

**Comment by xrotwang** [comment]
Btw. looking over all instances of `ET.SubElement` calls, I noticed one where a tag `dist` was created - not `distr` or `distribution`. Dunno if that's a bug, but it was the only instance such a tag was created.

**Comment by xrotwang** [comment]
And now I can ask the IDE to show all places where `xml.dist` was used - and can easily refactor if that's a bug.

**Comment by lmaurits** [comment]
If it's in the BSVS model, for an operator, then it's correct.

**Pull request merged**
