### PR TITLE
Interpolation

### LINKED ISSUE #56: Interpolation in configuration files
I think we are currently parsing configuration files explicitly without interpolation. Is there a good reason for that, or can I just switch interpolation on? I assume it's a good feature eg. for setting up a type of analysis and filling in some family-specific blanks using another config file that just sets a few lineage-dependent variables.

### LINKED ISSUE #121: BEASTling documentation does not talk about multiple config files
As we know, it's possible to use multiple config files together.

I just wanted to write a config file to add a new model and dataset to an existing config and wanted to make sure, by checking the docs, that the rightmost specified config overrides the left ones (when given on the command line) and whether I could do something like

    [admin]
    basename = %(basename)_with_typology

to just *extend* basename. (Note: Interpolation is also not mentioned in the docs.)

### PR DESCRIPTION
**Pull request by Anaphory**
Fixes #56 
Fixes #121

### CODE REVIEW

**Comment by Anaphory** [comment]
The lines that aren't covered are taken verbatim from `ConfigParser`, without any overall changes to functionality. I mean, we could write tests for duplicate sections, comments, etc. if you want, but I claim we don't need to.

**Review by xrotwang — COMMENTED** [review]
Personally, I wouldn't feel comfortable overwriting stuff not only from  one python standard library module, but from one that changed considerably between py2 and py3 and has been backported. Too many moving parts for my taste. I also think it puts quite a bit of burden on you in terms of documentation. Being able to say: "Hey, it's just python's configparser" seems a big win to me.

So overall, I think this is a bit of move away from the "simple things should be simple" goal, in order to get towards "complex things should be possible".

**Comment by Anaphory** [comment]
I agree that this situation is not ideal. When I saw that `Interpolation`s have a `before_read` method, I expected that I would not need to do this, but due to how it is implemented, it does not keep the promise it implicitly makes. I postulate the original implementors of `ConfigParser` were very much focussing on round-tripping and added the `before_read` method only as an afterthought – it's not really documented and I consider its calling behaviour a bug in the python standard library and have raised an issue about it.

So yes, this pull request is a significant change, and that's why I value you looking at it closely. That being said, let me try to convince you that the points you raise are important, but not crucially disabling.

- This delve into `ConfigParser` code comes from a use-based need to deal with the basenames of modular config files in a fast and transparent way. I definitely appreciate the possibility of complex things I have gained here. It has potential valuable use cases beyond mine.

- We are consistently using the backports version, so I think we are beyond the py2 vs py3 issues.

- Well, kind of. We are actually using `clldutils.inifile.INI`. It does not have documentation, we are not using its (untested) list functionality, and is already another moving part added. (In fact, the lists may break things for people who are assuming they have a standard python `ConfigParser`. I need to try that.)

- I think I have properly documented, commented and tested the behaviour that differs from configparser. I have tried to find the unittests for configparser, and if I found them, I'd be confident I could just add them and see them pass.

**Comment by xrotwang** [comment]
Wouldn't it be possible to factor merging of config files out into a separate library? I feel that merging of configuration, including interpolation, goes a bit against the spirit of BEASTling, which seems to me: There's one file which can be inspaected (and put into version control) which defines what BEAST is going to do. If there are multiple files, and non-trivial code required to merge them, this goal isn't really met. So, how about having your code living in a separate library, which has a cli interface that spits out the merged and interpolated config?

**Comment by xrotwang** [comment]
If you don't want to deal with the administrative issues of a new python package, this may even live within `clldutils`.

**Comment by Anaphory** [comment]
That might work. I was thinking of suggesting a separate python library whose API beastling could use, but actually also providing a CLI does sound decent.

It would change the call from
```
$ beastling config1 config2 config3
```
to
```
config_combiner config1 config2 config3 | beastling stdin
```
or something like that, which looks acceptable. (Beastling would have to get a way to read a config from stdin, not just data.)

**Comment by xrotwang** [comment]
It may also work to factor the code out into a separate command within BEASTling. But I think having BEASTling proper read **one** config file is a good feature to keep.`

**Comment by Anaphory** [comment]
Just to note, BEASTling has for very long time been able to read multiple config files, and in theory there have been non-obvious interactions between them. (Which one is read first/which one overrides?)

**Comment by xrotwang** [comment]
Yes, and I'm leaning towards considering this a mis-feature.

**Comment by Anaphory** [comment]
Taking it out from the CLI will be extremely easy, and not missed once `config_combiner` and `beastling stdin` exist.

Taking it out from the python API and from our testing environment would be a lot of work.

**Comment by Anaphory** [comment]
Check out #140 for a new approach to this.

**Comment by Anaphory** [comment]
#140 looks a lot more reasonable than this now. Closing this.

**Pull request closed without merging**
